CREATE TABLE PROVIDER (
  ID BIGINT(20) NOT NULL AUTO_INCREMENT,
  FIRST_NAME VARCHAR(500) NOT NULL,
  LAST_NAME VARCHAR(500) NOT NULL,
  EMAIL VARCHAR(500) NOT NULL,
  PASSWORD VARCHAR(500) NOT NULL,
  PRIMARY_PHONE VARCHAR(500) NOT NULL,
  ALTERNATE_PHONE VARCHAR(500) NOT NULL,
  PRIMARY KEY (ID)
)ENGINE=InnoDB DEFAULT CHARSET=latin1;

CREATE TABLE PROPERTY (
  ID_PROPERTY BIGINT(20) NOT NULL AUTO_INCREMENT,
  VENUE_NAME VARCHAR(500) NOT NULL,
  ADDRESS_LINE_1 VARCHAR(500) NOT NULL,
  ADDRESS_LINE_2 VARCHAR(500) DEFAULT NULL,
  LAND_MARK VARCHAR(500) DEFAULT NULL,
  CITY VARCHAR(500) NOT NULL,
  STATE VARCHAR(500) NOT NULL,
  COUNTRY VARCHAR(500) NOT NULL,
  POSTAL_CODE VARCHAR(500) NOT NULL,
  ID_PROVIDER BIGINT(20) NOT NULL,
  PRIMARY KEY (ID_PROPERTY),
  FOREIGN KEY (ID_PROVIDER) REFERENCES PROVIDER(ID)
)ENGINE=InnoDB DEFAULT CHARSET=latin1;
